title: "Train spancat pipelines on LitBank entity annotations."
description: >
  Train CNN and TRF pipelines on LitBank entity annotation comparing n-gram,
  subtree, and span finder suggesters.

directories: ["configs", "assets", "corpus", "training", "scripts", "metrics", "packages"]

vars:
  train_ratio: 0.8
  dev_ratio: 0.1
  seed: 83
  gpu: -1  # 0 to enable GPU
  version: "0.0.1"

assets:
  - dest: "assets/entities/"
    git:
      repo: "https://github.com/dbamman/litbank"
      branch: "master"
      path: "entities/brat/"
  
workflows:
  prepare:
    - prepare-entities
    - download-lg
    - download-trf

  ngram_lg:
    - train-spancat_ngram_lg
    - evaluate-spancat_ngram_lg
    - package-spancat_ngram_lg

  train-all:
    - train-spancat_ngram_lg
    - evaluate-spancat_ngram_lg
    - train-spancat_subtree_lg
    - evaluate-spancat_subtree_lg
    - train-spancat_span_finder_lg
    - evaluate-spancat_span_finder_lg
    - train-spancat_ngram_trf
    - evaluate-spancat_ngram_trf
    - train-spancat_subtree_trf
    - evaluate-spancat_subtree_trf
    - train-spancat_span_finder_trf
    - evaluate-spancat_span_finder_trf

  package-all:
    - package-spancat_ngram_lg
    - package-spancat_subtree_lg
    - package-spancat_span_finder_lg
    - package-spancat_ngram_trf
    - package-spancat_subtree_trf
    - package-spancat_span_finder_trf
  

commands:
  - name: "prepare-entities"
    help: "Prepare the LitBank entities for use in spaCy."
    script:
      - >-
        python -m scripts.prepare prepare-brat -i assets/entities
        -o corpus/entity_spans.spacy -l en -s entities -f
      - >- 
        python -m scripts.prepare split -i corpus/entity_spans.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
    deps:
      - assets/entities
    outputs:
      - corpus/entity_spans.spacy
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
      - corpus/entity_spans-test.spacy

  - name: "download-lg"
    help: "Download lg pipeline for vectors and subtree suggester"
    script:
      - python -m spacy download en_core_web_lg

  - name: "download-trf"
    help: "Download trf pipeline for subtree suggester"
    script:
      - python -m spacy download en_core_web_trf

  - name: "train-spancat_ngram_lg"
    script:
      - >-
        python -m spacy train
        configs/spancat_ngram_lg.cfg
        --output training/spancat_ngram_lg
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/spancat_ngram_lg.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_ngram_lg
  
  - name: "evaluate-spancat_ngram_lg"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_ngram_lg/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_ngram_lg.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_ngram_lg/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_ngram_lg.json

  - name: "package-spancat_ngram_lg"
    script:
      - mkdir -p packages/spancat_ngram_lg
      - >-
        python -m spacy package
        training/spancat_ngram_lg/model-best
        packages/spancat_ngram_lg
        --version ${vars.version}
        --name litbank_spancat_ngram_lg
        --build wheel
    deps:
      - training/spancat_ngram_lg/model-best

  - name: "train-spancat_span_finder_lg"
    script:
      - >-
        python -m spacy train
        configs/span_finder_lg.cfg
        --output training/span_finder_lg
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
      - >-
        python -m spacy train
        configs/spancat_span_finder_lg.cfg
        --output training/spancat_span_finder_lg
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/span_finder_lg.cfg
      - configs/spancat_span_finder_lg.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_span_finder_lg
  
  - name: "evaluate-spancat_span_finder_lg"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_span_finder_lg/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_span_finder_lg.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_span_finder_lg/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_span_finder_lg.json

  - name: "package-spancat_span_finder_lg"
    script:
      - mkdir -p packages/spancat_span_finder_lg
      - >-
        python -m spacy package
        training/spancat_span_finder_lg/model-best
        packages/spancat_span_finder_lg
        --version ${vars.version}
        --name litbank_spancat_span_finder_lg
        --build wheel
    deps:
      - training/spancat_span_finder_lg/model-best

  - name: "train-spancat_subtree_lg"
    script:
      - >-
        python -m spacy train
        configs/spancat_subtree_lg.cfg
        --output training/spancat_subtree_lg
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/spancat_subtree_lg.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_subtree_lg
  
  - name: "evaluate-spancat_subtree_lg"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_subtree_lg/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_subtree_lg.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_subtree_lg/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_subtree_lg.json

  - name: "package-spancat_subtree_lg"
    script:
      - mkdir -p packages/spancat_subtree_lg
      - >-
        python -m spacy package
        training/spancat_subtree_lg/model-best
        packages/spancat_subtree_lg
        --version ${vars.version}
        --name litbank_spancat_subtree_lg
        --build wheel
    deps:
      - training/spancat_subtree_lg/model-best

  - name: "train-spancat_ngram_trf"
    script:
      - >-
        python -m spacy train
        configs/spancat_ngram_trf.cfg
        --output training/spancat_ngram_trf
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/spancat_ngram_trf.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_ngram_trf
  
  - name: "evaluate-spancat_ngram_trf"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_ngram_trf/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_ngram_trf.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_ngram_trf/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_ngram_trf.json

  - name: "package-spancat_ngram_trf"
    script:
      - mkdir -p packages/spancat_ngram_trf
      - >-
        python -m spacy package
        training/spancat_ngram_trf/model-best
        packages/spancat_ngram_trf
        --version ${vars.version}
        --name litbank_spancat_ngram_trf
        --build wheel
    deps:
      - training/spancat_ngram_trf/model-best

  - name: "train-spancat_subtree_trf"
    script:
      - >-
        python -m spacy train
        configs/spancat_subtree_trf.cfg
        --output training/spancat_subtree_trf
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/spancat_subtree_trf.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_subtree_trf
  
  - name: "evaluate-spancat_subtree_trf"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_subtree_trf/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_subtree_trf.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_subtree_trf/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_subtree_trf.json

  - name: "package-spancat_subtree_trf"
    script:
      - mkdir -p packages/spancat_subtree_trf
      - >-
        python -m spacy package
        training/spancat_subtree_trf/model-best
        packages/spancat_subtree_trf
        --version ${vars.version}
        --name litbank_spancat_subtree_trf
        --build wheel
    deps:
      - training/spancat_subtree_trf/model-best

  - name: "train-spancat_span_finder_trf"
    script:
      - >-
        python -m spacy train
        configs/span_finder_trf.cfg
        --output training/span_finder_trf
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
      - >-
        python -m spacy train
        configs/spancat_span_finder_trf.cfg
        --output training/spancat_span_finder_trf
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/span_finder_trf.cfg
      - configs/spancat_span_finder_trf.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_span_finder_trf
  
  - name: "evaluate-spancat_span_finder_trf"
    script:
      - >-
        python -m spacy evaluate
        training/spancat_span_finder_trf/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_span_finder_trf.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_span_finder_trf/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/spancat_span_finder_trf.json

  - name: "package-spancat_span_finder_trf"
    script:
      - mkdir -p packages/spancat_span_finder_trf
      - >-
        python -m spacy package
        training/spancat_span_finder_trf/model-best
        packages/spancat_span_finder_trf
        --version ${vars.version}
        --name litbank_spancat_span_finder_trf
        --build wheel
    deps:
      - training/spancat_span_finder_trf/model-best
