title: "Train spancat pipelines on LitBank entity and event annotations."

directories: ["configs", "assets", "corpus", "training", "scripts", "metrics"]

vars:
  train_ratio: 0.8
  dev_ratio: 0.1
  seed: 83
  config: "spancat"
  gpu: -1
  #config: "spancat_trf"
  #gpu: 0

assets:
  - dest: "assets/entities/"
    git:
      repo: "https://github.com/dbamman/litbank"
      branch: "master"
      path: "entities/brat/"
  
  - dest: "assets/events/"
    git:
      repo: "https://github.com/dbamman/litbank"
      branch: "master"
      path: "events/brat/"

workflows:
  prepare:
    - prepare-entities
    - prepare-events
    - download-vectors

  train-entities:
    - train-spancat-entities
    - evaluate-spancat-entities

  train-events:
    - train-spancat-events
    - evaluate-spancat-events

commands:
  - name: "prepare-entities"
    help: "Prepare the LitBank entities for use in spaCy."
    script:
      - >-
        python -m scripts.prepare prepare-brat -i assets/entities
        -o corpus/entity_spans.spacy -l en -s entities -f
      - >-
        python -m scripts.prepare spans2ents -i corpus/entity_spans.spacy
        -l en -f -s entities -o corpus/entity_ents.spacy
      - >- 
        python -m scripts.prepare split -i corpus/entity_spans.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
      - >- 
        python -m scripts.prepare split -i corpus/entity_ents.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
#      - >-
#        python -m spacy debug data configs/${vars.config}.cfg
#        --paths.train corpus/entity_spans-train.spacy
#        --paths.dev corpus/entity_spans-dev.spacy
#        --components.spancat.spans_key entities
    deps:
      - assets/entities
      - configs/${vars.config}.cfg
    outputs:
      - corpus/entity_spans.spacy
      - corpus/entity_ents.spacy
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
      - corpus/entity_spans-test.spacy
      - corpus/entity_ents-train.spacy
      - corpus/entity_ents-dev.spacy
      - corpus/entity_ents-test.spacy

  - name: "prepare-events"
    help: "Prepare the LitBank events for use in spaCy."
    script:
      - >-
        python -m scripts.prepare prepare-brat -i assets/events
        -o corpus/event_spans.spacy -l en -s events -f
      - >- 
        python -m scripts.prepare split -i corpus/event_spans.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
#      - >-
#        python -m spacy debug data configs/${vars.config}.cfg
#        --paths.train corpus/event_spans-train.spacy
#        --paths.dev corpus/event_spans-dev.spacy
#        --components.spancat.spans_key events
    deps:
      - assets/events
      - configs/${vars.config}.cfg
    outputs:
      - corpus/event_spans.spacy
      - corpus/event_spans-train.spacy
      - corpus/event_spans-dev.spacy
      - corpus/event_spans-test.spacy

  - name: "download-vectors"
    help: "Download en_core_web_lg for vectors"
    script:
      - python -m spacy download en_core_web_lg

  - name: "train-spancat-entities"
    help: "Train the spancat pipeline on the LitBank entities annotation."
    script:
      - >-
        python -m spacy train
        configs/${vars.config}.cfg
        --components.spancat.spans_key entities
        --components.spancat.suggester.sizes '[1,2,3,4,5,6,7,8]'
        --training.score_weights.spans_entities_f 1.0
        --training.score_weights.spans_entities_p 0.0
        --training.score_weights.spans_entities_r 0.0
        --output training/${vars.config}_entities
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/${vars.config}.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/${vars.config}_entities
  
  - name: "train-spancat-events"
    help: "Train spancat pipeline on the LitBank events annotation."
    script:
      - >-
        python -m spacy train
        configs/${vars.config}.cfg
        --components.spancat.spans_key events
        --components.spancat.suggester.sizes '[1]'
        --training.score_weights.spans_events_f 1.0
        --training.score_weights.spans_events_p 0.0
        --training.score_weights.spans_events_r 0.0
        --output training/${vars.config}_events
        --paths.train corpus/event_spans-train.spacy
        --paths.dev corpus/event_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/${vars.config}.cfg
      - corpus/event_spans-train.spacy
      - corpus/event_spans-dev.spacy
    outputs:
      - training/${vars.config}_events
  
  - name: "evaluate-spancat-entities"
    help: "Evaluate the spancat pipeline trained on entities."
    script:
      - >-
        python -m spacy evaluate
        training/${vars.config}_entities/model-best
        corpus/entity_spans-test.spacy
        --output metrics/${vars.config}_entities.json
        --gpu-id ${vars.gpu}
    deps:
      - training/${vars.config}_entities/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy
      - metrics/${vars.config}_entities.json

  - name: "evaluate-spancat-events"
    help: "Evaluate the spancat pipeline trained on events."
    script:
      - >-
        python -m spacy evaluate
        training/${vars.config}_events/model-best
        corpus/event_spans-test.spacy
        --output metrics/${vars.config}_events.json
        --gpu-id ${vars.gpu}
    deps:
      - training/${vars.config}_events/model-best
      - corpus/event_spans-test.spacy
    outputs:
      - corpus/event_spans-test.spacy
      - metrics/${vars.config}_events.json

  - name: "train-span-finder-entities"
    help: "Train the span finder pipeline on the LitBank entities annotation."
    script:
      - >-
        python -m spacy train
        configs/span_finder.cfg
        --training.score_weights.spans_entities_f 0.0
        --training.score_weights.spans_entities_p 0.2
        --training.score_weights.spans_entities_r 0.8
        --output training/span_finder_entities
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - configs/span_finder.cfg
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/span_finder_entities
