title: "Train spancat_singlelabel pipelines on LitBank entity and event annotations."


directories: ["configs", "assets", "corpus", "training", "scripts", "metrics"]

assets:
  - dest: "assets/entities/"
    git:
      repo: "https://github.com/dbamman/litbank"
      branch: "master"
      path: "entities/brat/"
  
  - dest: "assets/events/"
    git:
      repo: "https://github.com/dbamman/litbank"
      branch: "master"
      path: "events/brat/"

vars:
  train_ratio: 0.8
  dev_ratio: 0.1
  seed: 83
  gpu: 0


workflows:
  
  prepare:
    - prepare-entities
    - prepare-events

  train-pipeline:
    - train-entities
    - evaluate-entities
    - train-events
    - evaluate-events


commands:
  - name: "prepare-entities"
    help: "Prepare the LitBank entities for use in spaCy."
    script:
      - >-
        python -m scripts.prepare prepare-brat -i assets/entities
        -o corpus/entity_spans.spacy -l en -s sc -f
      - >-
        python -m scripts.prepare spans2ents -i corpus/entity_spans.spacy
        -l en -f -s sc -o corpus/entity_ents.spacy
      - >- 
        python -m scripts.prepare split -i corpus/entity_spans.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
      - >- 
        python -m scripts.prepare split -i corpus/entity_ents.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
      - >-
        python -m spacy debug data configs/spancat.cfg
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
      - >-
        python -m spacy debug data configs/spancat.cfg
        --paths.train corpus/event_spans-train.spacy
        --paths.dev corpus/event_spans-dev.spacy
    deps:
      - assets/entities
    outputs:
      - corpus/entity_spans.spacy
      - corpus/entity_ents.spacy
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
      - corpus/entity_spans-test.spacy
      - corpus/entity_ents-train.spacy
      - corpus/entity_ents-dev.spacy
      - corpus/entity_ents-test.spacy

  - name: "prepare-events"
    help: "Prepare the LitBank events for use in spaCy."
    script:
      - >-
        python -m scripts.prepare prepare-brat -i assets/events
        -o corpus/event_spans.spacy -l en -s events -f
      - >- 
        python -m scripts.prepare split -i corpus/event_spans.spacy
        -t ${vars.train_ratio} -d ${vars.dev_ratio}
        -l en -se ${vars.seed} --shuffle
    
    deps:
      - assets/events
    outputs:
      - corpus/event_spans.spacy
      - corpus/event_spans-train.spacy
      - corpus/event_spans-dev.spacy
      - corpus/event_spans-test.spacy


  - name: "train-entities"
    help: "Train the spancat_singlelabel pipeline on the LitBank entities annotation."
    script:
      - >-
        python -m spacy train
        configs/spancat_singlelabel.cfg
        --output training/spancat_singlelabel_entities
        --paths.train corpus/entity_spans-train.spacy
        --paths.dev corpus/entity_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - corpus/entity_spans-train.spacy
      - corpus/entity_spans-dev.spacy
    outputs:
      - training/spancat_singlelabel_entities
  
  - name: "train-events"
    help: "Train spancat_singlelabel pipeline on the LitBank events annotation."
    script:
      - >-
        python -m spacy train
        configs/spancat_singlelabel_events.cfg
        --output training/spancat_singlelabel_events
        --paths.train corpus/event_spans-train.spacy
        --paths.dev corpus/event_spans-dev.spacy
        --system.seed ${vars.seed}
        --gpu-id ${vars.gpu}
    deps:
      - corpus/event_spans-train.spacy
      - corpus/event_spans-dev.spacy
    outputs:
      - training/spancat_singlelabel_events
  
  - name: "evaluate-entities"
    help: "Evaluate the spancat_singlelabel pipeline trained on entities."
    script:
      - >-
        python -m spacy evaluate
        training/spancat_singlelabel_entities/model-best
        corpus/entity_spans-test.spacy
        --output metrics/spancat_singlelabel_entities.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_singlelabel_entities/model-best
      - corpus/entity_spans-test.spacy
    outputs:
      - corpus/entity_spans-test.spacy

  - name: "evaluate-events"
    help: "Evaluate the spancat_singlelabel pipeline trained on events."
    script:
      - >-
        python -m spacy evaluate
        training/spancat_singlelabel_events/model-best
        corpus/event_spans-test.spacy
        --output metrics/spancat_singlelabel_events.json
        --gpu-id ${vars.gpu}
    deps:
      - training/spancat_singlelabel_events/model-best
      - corpus/event_spans-test.spacy
    outputs:
      - corpus/event_spans-test.spacy
